// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCp2Cg1DcmVhdHVyZVN0YXRlEhcKE0NS",
            "RUFUVVJFX1NUQVRFX0lETEUQABIZChVDUkVBVFVSRV9TVEFURV9NT1ZJTkcQ",
            "ARIYChRDUkVBVFVSRV9TVEFURV9TS0lMTBACEhcKE0NSRUFUVVJFX1NUQVRF",
            "X0RFQUQQA0IbqgIYR29vZ2xlLlByb3RvYnVmLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.CreatureState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CreatureState {
    [pbr::OriginalName("CREATURE_STATE_IDLE")] Idle = 0,
    [pbr::OriginalName("CREATURE_STATE_MOVING")] Moving = 1,
    [pbr::OriginalName("CREATURE_STATE_SKILL")] Skill = 2,
    [pbr::OriginalName("CREATURE_STATE_DEAD")] Dead = 3,
  }

  #endregion

}

#endregion Designer generated code
